version: '3'

services:
  app:
    image: zmiterr/q4-service
    container_name: q4-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - user-defined-bridge
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ./src:/usr/app/src
      - logs:/usr/app/logs
    environment:
      PORT: ${PORT}
  postgres:
    image: postgres
    container_name: postgres
    build: ./db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - user-defined-bridge
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}


networks:
  user-defined-bridge:
    driver: bridge

volumes:
  logs:
  db:

